DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:72 Selenium Manager binary found at: C:\Users\zoltan\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Executing process: C:\Users\zoltan\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 chromedriver not found in PATH
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Output: "\r\r\n\r\r\nVersion=120.0.6099.225\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Detected browser: chrome 120.0.6099.225
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Required driver: chromedriver 120.0.6099.109
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 chromedriver 120.0.6099.109 already in the cache
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Driver path: C:\Users\zoltan\.cache\selenium\chromedriver\win64\120.0.6099.109\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:146 Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:107 Using driver at: C:\Users\zoltan\.cache\selenium\chromedriver\win64\120.0.6099.109\chromedriver.exe
DEBUG    selenium.webdriver.common.service:service.py:219 Started executable: `C:\Users\zoltan\.cache\selenium\chromedriver\win64\120.0.6099.109\chromedriver.exe` in a child process with pid: 11252 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:54269/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "browserVersion": null, "goog:chromeOptions": {"extensions": [], "binary": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "args": []}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:54269
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:54269 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"120.0.6099.225","chrome":{"chromedriverVersion":"120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483})","userDataDir":"C:\\Users\\zoltan\\AppData\\Local\\Temp\\scoped_dir11252_1889805514"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:54273"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"f62a8a40aa3a8c940a067b5f50d7020f"}} | headers=HTTPHeaderDict({'Content-Length': '885', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
